FROM ubi9:latest

LABEL maintainer Zucchini Universe <zucchini@zucchiniuniverse.org>

RUN dnf -y update --noplugins \
    dnf -y --noplugins install dnsmasq
    
# Add this packages for troubleshooting: iproute

ENTRYPOINT [ "dnsmasq", "-C", "/etc/dnsmasq.conf", "-d" ]
