version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    networks:
      - prod 
    volumes:
      - grafana_data:/var/lib/grafana
      - grafana_logs:/var/log/grafana

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - prod
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - "--log.level=debug"
      - "--config.file=/etc/prometheus/prometheus.yml"

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    networks:
      - prod

volumes:
  grafana_data:
  grafana_logs:
  prometheus_data:


networks:
  prod:
