FROM alpine:latest

ARG ZUCCHINI_USER=zucchini
ARG ZUCCHINI_GECOS="Zucchini Universe"
ARG ZUCCHINI_HOME=/home/zucchini
ARG ZUCCHINI_UID=1305
ENV PANEL_VERSION=latest \
    APP_ROOT=${ZUCCHINI_HOME}/panel \
    LOGS_ROOT=${ZUCCHINI_HOME}/logs \
    BIN_ROOT=${ZUCCHINI_HOME}/bin \
    TMP_ROOT=${ZUCCHINI_HOME}/tmp \
    SSL_ROOT=${ZUCCHINI_HOME}/ssl \
    LISTEN_ADDRESS=0.0.0.0:9000

COPY ./files ${ZUCCHINI_HOME}

RUN adduser -D ${ZUCCHINI_USER} -h ${ZUCCHINI_HOME} -g ${ZUCCHINI_GECOS} -u ${ZUCCHINI_UID} \
    && apk update && apk add bash supervisor curl \
    php7 php7-curl php7-dom php7-fpm php7-fileinfo php7-json php7-openssl php7-gd php7-mbstring php7-pdo_mysql \
    php7-zip php7-simplexml php7-tokenizer php7-bcmath php7-curl php7-phar php7-session php7-xml php7-xmlwriter \
    && rm -f /etc/supervisord.conf && ln -s ${ZUCCHINI_HOME}/etc/supervisord.conf /etc/supervisord.conf \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && mkdir -p ${APP_ROOT} && chown -R ${ZUCCHINI_USER}:${ZUCCHINI_USER} ${ZUCCHINI_HOME} 

USER ${ZUCCHINI_USER}

WORKDIR ${APP_ROOT}

RUN curl -Lo "panel_${PANEL_VERSION}.tar.gz" https://github.com/pterodactyl/panel/releases/latest/download/panel.tar.gz \
    && tar -xzvf panel_${PANEL_VERSION}.tar.gz && rm "panel_${PANEL_VERSION}.tar.gz" \
    && chmod -R 755 storage/* bootstrap/cache \
    && echo "APP_KEY=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)" > .env \
    && composer install --ansi --no-dev --optimize-autoloader

RUN rm -rf ${APP_ROOT}/storage \
    && mkdir -p ${APP_ROOT}/storage/app/packs \
    && mkdir -p ${APP_ROOT}/storage/framework/cache/data \
    && mkdir -p ${APP_ROOT}/storage/framework/sessions \
    && mkdir -p ${APP_ROOT}/storage/framework/views \
    && mkdir -p ${LOGS_ROOT}/supervisord \
    && mkdir -p ${LOGS_ROOT}/php7-fpm \
    && mkdir -p ${LOGS_ROOT}/panel \
    && mkdir -p ${TMP_ROOT} \
    && ln -s ${LOGS_ROOT}/panel ${APP_ROOT}/storage/logs \
    && rm -rf ${APP_ROOT}/bootstrap/cache \
    && ln -s ${APP_ROOT}/storage/framework/cache ${APP_ROOT}/bootstrap/cache \
    && find ${ZUCCHINI_HOME} -path ${APP_ROOT} -prune -o -type f -exec sed -i "s@PANEL_ROOT@${ZUCCHINI_HOME}@g" '{}' ';' \
    && find ${ZUCCHINI_HOME} -path ${APP_ROOT} -prune -o -type f -exec sed -i "s@TMP_ROOT@${TMP_ROOT}@g" '{}' ';' \
    && find ${ZUCCHINI_HOME} -path ${APP_ROOT} -prune -o -type f -exec sed -i "s@BIN_ROOT@${BIN_ROOT}@g" '{}' ';' \
    && find ${ZUCCHINI_HOME} -path ${APP_ROOT} -prune -o -type f -exec sed -i "s@SSL_ROOT@${SSL_ROOT}@g" '{}' ';' \
    && find ${ZUCCHINI_HOME} -path ${APP_ROOT} -prune -o -type f -exec sed -i "s@APP_ROOT@${APP_ROOT}@g" '{}' ';' \
    && find ${ZUCCHINI_HOME} -path ${APP_ROOT} -prune -o -type f -exec sed -i "s@LOGS_ROOT@${LOGS_ROOT}@g" '{}' ';' \
    && find ${ZUCCHINI_HOME} -path ${APP_ROOT} -prune -o -type f -exec sed -i "s@PANEL_USER@${ZUCCHINI_USER}@g" '{}' ';' \
    && find ${ZUCCHINI_HOME} -path ${APP_ROOT} -prune -o -type f -exec sed -i "s@LISTEN_ADDRESS@${LISTEN_ADDRESS}@g" '{}' ';' \
    && find ${ZUCCHINI_HOME} -type d -exec chmod 750 '{}' ';' \
    && find ${ZUCCHINI_HOME} -type f -exec chmod 640 '{}' ';' \
    && chmod +x ${APP_ROOT}/artisan \
    && chmod 750 ${BIN_ROOT}/entrypoint.sh

ENTRYPOINT [ "../bin/entrypoint.sh" ]
