version: '3'

services:
  mariadb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=pikachu
      - MYSQL_DATABASE=pikachu
      - MYSQL_USER=pikachu
      - MYSQL_PASSWORD=pikachu
    networks:
      - prod
    volumes:
      - dbdata:/var/lib/mysql

  panel:
    image: zucchini-panel:latest
    networks:
      - prod
    tty: true
    volumes:
      - app:/home/pikachu/panel
      - logs:/home/pikachu/logs
      - ./conf/panel/pikachu-panel-dev.env:/home/pikachu/panel/.env
    depends_on:
      - mariadb
      - redis

  redis:
    image: redis:alpine
    networks:
      - prod
    volumes:
      - cachedata:/data

networks:
  prod:
    external:
      name: web_prod

volumes:
  dbdata:
  cachedata:
  app:
  logs:
