version: '3.8'
services:
  nginx:
    image: zucchini-nginx:latest
    ports:
      - 80:80
      - 443:443
    networks:
      - prod
    volumes:
      - ./certs:/home/zucchini/certs
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./sites:/www
      - panel:/home/zucchini/panel

networks:
  prod:

volumes:
  panel:
    external: true
    name: panel_app
