version: '3'
services:
  daemon:
    image: zucchini-wings:latest
    ports:
      - "18080:18080"
      - "12022:12022"
    tty: true
    volumes:
      - /home/elmorti/certs:/home/zucchini/certs
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/wings:/srv/wings
      - /tmp/pterodactyl:/tmp/pterodactyl
      - ~/github/zucchini-configs/certs/elmorti.org/fullchain.cer:/etc/letsencrypt/live/elmorti004.elmorti.org/fullchain.pem
      - ~/github/zucchini-configs/certs/elmorti.org/elmorti.org.key:/etc/letsencrypt/live/elmorti004.elmorti.org/privkey.pem
      - ~/github/zucchini-configs/pterodactyl/wings/elmorti004.config.yml:/etc/pterodactyl/config.yml
      - /usr/bin/timedatectl:/usr/bin/timedatectl
